lang: ja
url: http://ja.onsenui.io
title: HTML5モバイルアプリをもっと速く、もっと美しく Onsen UI
description: Onsen UI from Monaca is a Custom Elements-Based HTML5 UI Framework for Building PhoneGap/Cordova Hybrid apps
keywords: phonegap, cordova, custom-elements, onsen, ui, html5, monaca, framework, mobile, app, hybrid, simple, powerful, fast
twitter: Onsen UIでHTML5モバイルアプリをもっと速く、美しく。
